# Generated by Django 5.1.4 on 2024-12-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0003_rename_examuser_examprofile_rename_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileolympiad',
            old_name='user',
            new_name='profile',
        ),
    ]
