# Generated by Django 5.1.4 on 2024-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0004_rename_user_profileolympiad_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='related_file_path',
        ),
        migrations.AddField(
            model_name='exam',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/'),
        ),
    ]
