# Generated by Django 5.1.4 on 2024-12-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0006_president_alter_exam_related_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilegroup',
            old_name='user',
            new_name='profile',
        ),
    ]
