# Generated by Django 5.1.4 on 2024-12-08 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0007_rename_user_profilegroup_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('school_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilegroup',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profileolympiad',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilegroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profileolympiad',
            name='olympiad',
        ),
        migrations.AlterField(
            model_name='groupexam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_exams', to='tbot.group'),
        ),
        migrations.AlterField(
            model_name='olympiadsubject',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_subjects', to='tbot.olympiad'),
        ),
        migrations.CreateModel(
            name='ExamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_students', to='tbot.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbot.student')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='related_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbot.student'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='tbot.student'),
        ),
        migrations.CreateModel(
            name='StudentOlympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbot.olympiad')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_olympiad', to='tbot.student')),
            ],
        ),
        migrations.AlterField(
            model_name='teachergroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to='tbot.teacher'),
        ),
        migrations.DeleteModel(
            name='ExamProfile',
        ),
        migrations.DeleteModel(
            name='ProfileGroup',
        ),
        migrations.DeleteModel(
            name='ProfileOlympiad',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
