# Generated by Django 5.1.4 on 2024-12-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0008_student_teacher_remove_profilegroup_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='examfiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='related_file',
        ),
        migrations.AddField(
            model_name='answer',
            name='related_files',
            field=models.ManyToManyField(related_name='answer_files', to='tbot.file'),
        ),
        migrations.AddField(
            model_name='exam',
            name='files',
            field=models.ManyToManyField(related_name='exam_files', to='tbot.file'),
        ),
    ]
