# Generated by Django 5.1.4 on 2024-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0009_file_remove_exam_related_file_answer_related_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='files',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='related_files',
        ),
        migrations.AddField(
            model_name='exam',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='examfiles/'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='answer',
            name='related_files',
            field=models.FileField(blank=True, null=True, upload_to='examfiles/'),
        ),
    ]
