# Generated by Django 5.1.4 on 2024-12-12 16:21

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0010_remove_exam_files_remove_answer_related_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='submission_time',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='time_started_exam',
        ),
        migrations.AddField(
            model_name='answer',
            name='duration',
            field=models.DurationField(default=now()-now()),
        ),
    ]
