# Generated by Django 5.1.4 on 2024-12-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0012_alter_answer_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='duration',
            new_name='duration_seconds',
        ),
    ]
