# Generated by Django 5.1.4 on 2024-12-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0013_rename_duration_answer_duration_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoresheet',
            old_name='answer',
            new_name='related_answer',
        ),
        migrations.RenameField(
            model_name='scoresheet',
            old_name='exam',
            new_name='related_exam',
        ),
        migrations.AddField(
            model_name='answer',
            name='related_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tbot.exam'),
        ),
    ]
