# Generated by Django 5.1.4 on 2024-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0016_rename_related_files_answer_related_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
