# Generated by Django 5.1.4 on 2024-12-14 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0017_alter_answer_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='duration',
        ),
        migrations.AddField(
            model_name='answer',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='related_message_id',
            field=models.CharField(blank=True, max_length=2250),
        ),
        migrations.AddField(
            model_name='answer',
            name='related_student_chat_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='time_ended',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='examfiles/answerfiles'),
        ),
    ]
