# Generated by Django 5.1.4 on 2024-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0018_remove_answer_duration_answer_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='related_groups',
            field=models.ManyToManyField(related_name='exam_groups', to='tbot.group'),
        ),
    ]
