# Generated by Django 5.1.4 on 2024-12-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0019_exam_related_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoresheet',
            name='related_exam',
        ),
    ]
