# Generated by Django 5.1.4 on 2024-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0020_remove_scoresheet_related_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='score',
            field=models.FloatField(),
        ),
    ]
