# Generated by Django 5.1.4 on 2024-12-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0021_answer_is_rated_alter_scoresheet_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='related_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheet', to='tbot.answer'),
        ),
    ]
