# Generated by Django 5.1.4 on 2024-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0022_alter_scoresheet_related_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
